// apps/web/shared/components/Link.vue
<template>
  <a :href="_href" v-bind="rest" />
</template>

<script setup lang="ts">
import { type Locale, baseLocale } from '#modules/locales/locales.utils';
import { usePageContext } from '#modules/providers/vike.provider';
import type { LinkHTMLAttributes } from 'vue';

interface Props extends LinkHTMLAttributes {
  locale: Locale
}
defineOptions({
  inheritAttrs: false,
})
defineProps<Props>()

const { locale, href, ...rest } = useAttrs() as Record<string, any>
const pageContext = usePageContext()

const _href = computed<string>(() => (locale || pageContext.locale) !== baseLocale ? `/${locale}${href}` : href)

</script>

// src/shared/components/Link.tsx
import { usePageContext } from "@techmely/vike-react/usePageContext";
import type { AnchorHTMLAttributes, DetailedHTMLProps, FC } from "react";
import { type Locale, baseLocale } from "#root/locales/locales.utils";

type Props = DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement> & {
  locale?: Locale;
};

const Link: FC<Props> = ({ href, locale, ...props }) => {
  const pageContext = usePageContext();
  locale = locale || (pageContext.metadata?.locale as Locale);
  if (locale !== baseLocale) {
    href = `/${locale}${href}`;
  }
  return <a href={href} {...props} />;
};

export default Link;
